import Footer from '../app/components/footer';
import Navbar from '../app/components/Navbar';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ProjetoGames",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-BR"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body style={{ display: 'flex',flexDirection: 'column',minHeight: '100vh',margin: 0,}} 
        className="min-h-full flex flex-col">
      <Navbar/>
      <main style={{ flex: 1 }}>{children}</main>
       <Footer/>
      </body>
    </html>
  );
} 